update melpazoid tests in github actions

diff --git a/.github/workflows/melpazoid.yml b/.github/workflows/melpazoid.yml
--- a/.github/workflows/melpazoid.yml
+++ b/.github/workflows/melpazoid.yml
@@ -9,21 +9,38 @@ name: melpazoid
 jobs:
   build:
     runs-on: ubuntu-latest
+    strategy:
+      fail-fast: false
+      matrix:
+        emacs_version:
+          - 27.2
+          - 28.1
+          - 28.2
+          - 29.1
+          - 29.2
+          - 29.3
+          - 29.4
+          - 30.1
+          - release-snapshot
     steps:
       - name: Get repo to access in conteiner
         uses: actions/checkout@v5
         with:
-          fetch-depth: 0
+          fetch-depth: 1
       - name: Set up Python 3.12
         uses: actions/setup-python@v5
         with:
           python-version: 3.12
-      - name: Install
+      - name: Install melpazoid
         run: |
           python -m pip install --upgrade pip
-          sudo apt-get install emacs-nox  && emacs --version
+          # sudo apt-get install emacs-nox && emacs --version
           git clone https://github.com/riscy/melpazoid.git ~/melpazoid
           pip install ~/melpazoid
+      - name: Install Emacs
+        uses: purcell/setup-emacs@master
+        with:
+          version: ${{ matrix.emacs_version }}
       - name: Tests
         run: |
          emacs -Q --batch -l ert.el -l org-links.el -l org-links-tests.el -f ert-run-tests-batch-and-exit
@@ -46,6 +63,9 @@ jobs:
           fi
           if grep -q ' with [melpazoid]' output.log ; then
             echo "Melpazoid warning detected, failing workflow" ; exit 1
+          fi
+          if grep -q ' with package-lint ' output.log ; then
+            echo "Checkdoc warning detected, failing workflow" ; exit 1
           fi
           if grep -q ' with checkdoc ' output.log ; then
             echo "Checkdoc warning detected, failing workflow" ; exit 1
